<?php
//landing theme

$statewide_races = array(
  /*'_cmb_ballot_president-and-vice-president-of-the-united-states',
  '_cmb_ballot_us-senate',
  '_cmb_ballot_nc-governor',
  '_cmb_ballot_nc-lieutenant-governor',
  '_cmb_ballot_nc-attorney-general',
  '_cmb_ballot_nc-auditor',
  '_cmb_ballot_nc-commissioner-of-agriculture',
  '_cmb_ballot_nc-commissioner-of-insurance',
  '_cmb_ballot_nc-commissioner-of-labor',
  '_cmb_ballot_nc-secretary-of-state',
  '_cmb_ballot_nc-superintendent-of-public-instruction',
  '_cmb_ballot_nc-treasurer',*/
  '_cmb_ballot_nc-supreme-court-associate-justice',
  //'_cmb_ballot_nc-court-of-appeals-judge-stephens-seat',
  //'_cmb_ballot_nc-court-of-appeals-judge-dietz-seat',
  //'_cmb_ballot_nc-court-of-appeals-judge-hunter-seat',
  //'_cmb_ballot_nc-court-of-appeals-judge-zachary-seat',
 // '_cmb_ballot_nc-court-of-appeals-judge-geer-seat',
  '_cmb_ballot_nc-court-of-appeals-judge-seat-1',
  '_cmb_ballot_nc-court-of-appeals-judge-seat-2',
  '_cmb_ballot_nc-court-of-appeals-judge-seat-3',
  '_cmb_ballot_constitutional-amendment-1-0',
  '_cmb_ballot_constitutional-amendment-2-1',
  '_cmb_ballot_constitutional-amendment-3-2',
  '_cmb_ballot_constitutional-amendment-4-3',
  '_cmb_ballot_constitutional-amendment-5-4',
  '_cmb_ballot_constitutional-amendment-6-5',
  '_cmb_ballot_issue-1-0',
  '_cmb_ballot_issue-2-1',
  '_cmb_ballot_issue-3-2',
  '_cmb_ballot_issue-4-3',
  '_cmb_grade',
  '_cmb_gender',
  '_cmb_race',
  '_cmb_adults_vote',
  '_cmb_register',
  '_cmb_party',
  '_cmb_news',
  '_cmb_religious',
  '_cmb_living',
  '_cmb_participation'
);
